{% set name = "mediapy" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mediapy-{{ version }}.tar.gz
  sha256: bc3b79c1767a3ac0926f34a19be32cf63843e61ddb32f05e3173b198beb9b3b2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
    - flit-core
  run:
    - ipython
    - matplotlib-base
    - numpy
    - pillow
    - python >={{ python_min }}
    - ffmpeg


test:
  imports:
    - mediapy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/mediapy
  summary: Read/write/show images and videos in an IPython notebook
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
